### ISSUE TITLE
sync feature causes `grep` error on recent macos when using `-s` mode

### ISSUE THREAD

**Issue by zdAlexM** [greymd/tmux-xpanes#173] opened 2023-01-11 19:39 UTC
Hi,

I believe this started when upgrading to 12.5, but when using `xpanes -t -s -c 'ssh -F ssh.config {}' host1 host2 host3 etc`, the panes are opening with the following kind of error:
`grep: /Users/zdAlexM/.cache/xpanes/__xpns_sync_776f726b312e706f6432362e757365322e7a647379732e636f6d2d36373834320a-5-67842: No such file or directory`

where the digits vary per pane and session ID.

This does not happen if I leave out the `-s` option

The `.cache/xpanes` directory exists, and the sessions establish, but it looks like there's a race condition between creating the FIFO and expecting it. Unfortunately, adding `--debug` to the command line doesn't seem to produce any more logging output inside the pane, and the out-of-pane logs are not too informative as to the issue:

```
xpanes:Debug: [2023-01-11_11:26:17]:xpns_get_window_height_width:window height: 54, width: 175
xpanes:Debug: [2023-01-11_11:26:17]:xpns_check_cell_size:Window: { Height: 54, Width: 175 }
xpanes:Debug: [2023-01-11_11:26:17]:xpns_check_cell_size:Cell: { Height: 17, Width: 57 }
xpanes:Debug: [2023-01-11_11:26:17]:xpns_check_cell_size:# Of Panes: 9
xpanes:Debug: [2023-01-11_11:26:17]:xpns_check_cell_size:         | Row[0] --...--> Row[MAX]
xpanes:Debug: [2023-01-11_11:26:17]:xpns_check_cell_size:    -----+------------------------...
xpanes:Debug: [2023-01-11_11:26:17]:xpns_check_cell_size:    Col[]| 3 3 3 
xpanes:Debug: [2023-01-11_11:26:17]:xpns_check_cell_size:    -----+------------------------...
xpanes:Debug: [2023-01-11_11:26:17]:xpns_pre_execution:Options: '--debug' '-t' '-s' '-c' 'ssh -F ssh.config {}'
xpanes:Debug: [2023-01-11_11:26:17]:xpns_pre_execution:Arguments: 'host1' 'host2' 'host3' 'host4' 'host5' 'host6' 'host7' 'host8' 'host9'
xpanes:Debug: [2023-01-11_11:26:17]:xpns_clean_session:file = /Users/zdAlexM/.cache/xpanes/socket.*
xpanes:Debug: [2023-01-11_11:26:17]:xpns_clean_session:socket(/Users/zdAlexM/.cache/xpanes/socket.*) is not running. Remove it
[exited]
xpanes:Debug: [2023-01-11_11:26:21]:xpns_clean_session:file = /Users/zdAlexM/.cache/xpanes/socket.60843
xpanes:Debug: [2023-01-11_11:26:21]:xpns_clean_session:socket(/Users/zdAlexM/.cache/xpanes/socket.60843) is not running. Remove it
```

**Comment by greymd** [comment] 2023-01-12 11:18
In order to understand the situation in more detail,
could you check if the issue reproduces on a tmux session as shown below?

```bash
### open tmux session
$ tmux
```

```bash
### Try to reproduce issue on the tmux window with --debug
$ xpanes --debug -t -s -c 'ssh -F ssh.config {}' host1 host2 host3 etc...
```

This method would give a more detailed debug log on the tmux window.

**Comment by zdAlexM** [comment] 2023-01-12 16:17
Hi, @greymd

opening a `tmux` session without `xpanes` just opens my shell (which is fish shell, but that hasn't caused problems before), with no error.

Here is the debug output from inside that tmux session. The panes still display the same error about the sync fifo.

```
xpanes:Debug: [2023-01-12_08:11:16]:xpns_execution:Options: '--debug' '-t' '-s' '-c' 'ssh -F /Users/zdAlexM/.ssh/ssh.config {}'
xpanes:Debug: [2023-01-12_08:11:16]:xpns_execution:Arguments: 'host4' 'host5' 'host6'
xpanes:Debug: [2023-01-12_08:11:16]:xpns_wait_func:mkfifo /Users/zdAlexM/.cache/xpanes/__xpns_sync_68616c6f6e2d6f75742d70726f7879342e706f643939382d37383235320a-0-78252
xpanes:Debug: [2023-01-12_08:11:17]:xpns_wait_func:grep -q 1 '/Users/zdAlexM/.cache/xpanes/__xpns_sync_68616c6f6e2d6f75742d70726f7879342e706f643939382d37383235320a-0-78252'
xpanes:Debug: [2023-01-12_08:11:17]:xpns_prepare_window:_col=1
xpanes:Debug: [2023-01-12_08:11:17]:xpns_wait_func:mkfifo /Users/zdAlexM/.cache/xpanes/__xpns_sync_68616c6f6e2d6f75742d70726f7879342e706f643939382d37383235320a-2-78252
xpanes:Debug: [2023-01-12_08:11:17]:xpns_wait_func:grep -q 1 '/Users/zdAlexM/.cache/xpanes/__xpns_sync_68616c6f6e2d6f75742d70726f7879342e706f643939382d37383235320a-2-78252'
xpanes:Debug: [2023-01-12_08:11:17]:xpns_prepare_window:_top_pane_height=19 _rest_row=1
xpanes:Debug: [2023-01-12_08:11:17]:xpns_wait_func:mkfifo /Users/zdAlexM/.cache/xpanes/__xpns_sync_68616c6f6e2d6f75742d70726f7879342e706f643939382d37383235320a-1-78252
xpanes:Debug: [2023-01-12_08:11:17]:xpns_wait_func:grep -q 1 '/Users/zdAlexM/.cache/xpanes/__xpns_sync_68616c6f6e2d6f75742d70726f7879342e706f643939382d37383235320a-1-78252'
xpanes:Debug: [2023-01-12_08:11:17]:xpns_execution:xpns_is_window_alive:1: After window separation
xpanes:Debug: [2023-01-12_08:11:17]:xpns_execution:xpns_is_window_alive:2: After logging
xpanes:Debug: [2023-01-12_08:11:17]:xpns_inject_title:target_pane=68616c6f6e2d6f75742d70726f7879342e706f643939382d37383235320a.0 pane_title=host4 pane_tty=/dev/ttys014
xpanes:Debug: [2023-01-12_08:11:17]:xpns_inject_title:target_pane=68616c6f6e2d6f75742d70726f7879342e706f643939382d37383235320a.1 pane_title=host5 pane_tty=/dev/ttys019
xpanes:Debug: [2023-01-12_08:11:17]:xpns_inject_title:target_pane=68616c6f6e2d6f75742d70726f7879342e706f643939382d37383235320a.2 pane_title=host6 pane_tty=/dev/ttys018
xpanes:Debug: [2023-01-12_08:11:17]:xpns_notify:Notify to /Users/zdAlexM/.cache/xpanes/__xpns_sync_68616c6f6e2d6f75742d70726f7879342e706f643939382d37383235320a-1-78252
xpanes:Debug: [2023-01-12_08:11:17]:xpns_execution:xpns_is_window_alive:3: After setting title
xpanes:Debug: [2023-01-12_08:11:17]:xpns_notify:Notify to /Users/zdAlexM/.cache/xpanes/__xpns_sync_68616c6f6e2d6f75742d70726f7879342e706f643939382d37383235320a-0-78252
xpanes:Debug: [2023-01-12_08:11:17]:xpns_notify:Notify to /Users/zdAlexM/.cache/xpanes/__xpns_sync_68616c6f6e2d6f75742d70726f7879342e706f643939382d37383235320a-2-78252
xpanes:Debug: [2023-01-12_08:11:17]:xpns_execution:xpns_is_window_alive:4: After sending commands
xpanes:Debug: [2023-01-12_08:11:17]:xpns_clean_session:file = /Users/zdAlexM/.cache/xpanes/socket.57168
xpanes:Debug: [2023-01-12_08:11:17]:xpns_clean_session:socket(/Users/zdAlexM/.cache/xpanes/socket.57168) is running. Keep /Users/zdAlexM/.cache/xpanes/socket.57168
```

**Comment by greymd** [comment] 2023-01-12 22:31
That is interesting.
As far as checking the log, `mkfifo` seems to be executed before `grep` all the time.
In other words, the file that `grep` handles must exist.
But despite this, you are getting a `No such file or directory` error, right?

```
xpanes:Debug: [2023-01-12_08:11:16]:xpns_wait_func:mkfifo /Users/zdAlexM/.cache/xpanes/__xpns_sync_68616c6f6e2d6f75742d70726f7879342e706f643939382d37383235320a-0-78252
xpanes:Debug: [2023-01-12_08:11:17]:xpns_wait_func:grep -q 1 '/Users/zdAlexM/.cache/xpanes/__xpns_sync_68616c6f6e2d6f75742d70726f7879342e706f643939382d37383235320a-0-78252'
︙
```

Hmm..., to be honest, I am not sure of the cause.
But, one possible concern is that the `mkfifo` fails to create named pipe file.

Could you edit the `xpanes` executable file as follows and try to repro the issue on the tmux session again?

Edit [`xpns_wait_func` function](https://github.com/greymd/tmux-xpanes/blob/master/bin/xpanes#L795-L805).
```bash
xpns_wait_func() {
  local _wait_id="$1"
  local _fifo="${XP_CACHE_HOME}/__xpns_${_wait_id}"
  local _arr=("$_fifo")
  local _fifo_arg=
  _fifo_arg=$(xpns_arr2args "${_arr[@]}")
  xpns_msg_debug "mkfifo $_fifo"
  ## Comment out
  # mkfifo "${_fifo}"
  ## Add following 2 lines
  mkfifo "${_fifo}" >&2
  echo "mkfifo exit status = $?" >&2
  xpns_msg_debug "grep -q 1 ${_fifo_arg}"
  printf "%s\\n" "grep -q 1 ${_fifo_arg}"
}
```

You must get the log something like...

```
xpanes:Debug: [2023-01-12_22:23:43]:xpns_wait_func:mkfifo /Users/greymd/.cache/xpanes/__xpns_sync_75622d35363636330a-0-56663
mkfifo exit status = 0
xpanes:Debug: [2023-01-12_22:23:43]:xpns_wait_func:grep -q 1 '/Users/greymd/.cache/xpanes/__xpns_sync_75622d35363636330a-0-56663'
```

If the exit status is non-zero, something may be going on (If it is zero, it may be a tough problem, so we need to consider some workaround).

**Comment by greymd** [comment] 2023-01-12 22:33
By the way, is your environment macOS?
Can you share the following information along with your logs?

```
$ sysctl kern.version
$ /usr/bin/env bash -c 'type mkfifo'
$ /usr/bin/env bash --version
$ xpanes --version
```

**Comment by zdAlexM** [comment] 2023-01-12 22:47
My environment is MacOS. `xpanes` was installed via homebrew.

```
$ /usr/bin/env bash -c 'type mkfifo'
mkfifo is /usr/bin/mkfifo
$ /usr/bin/env bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.
$ xpanes --version
xpanes 4.1.3
```

The requested debug logs:

```
xpanes:Debug: [2023-01-12_14:42:09]:xpns_check_cell_size:Window: { Height: 53, Width: 175 }
xpanes:Debug: [2023-01-12_14:42:09]:xpns_check_cell_size:Cell: { Height: 26, Width: 87 }
xpanes:Debug: [2023-01-12_14:42:09]:xpns_check_cell_size:# Of Panes: 3
xpanes:Debug: [2023-01-12_14:42:09]:xpns_check_cell_size:         | Row[0] --...--> Row[MAX]
xpanes:Debug: [2023-01-12_14:42:09]:xpns_check_cell_size:    -----+------------------------...
xpanes:Debug: [2023-01-12_14:42:09]:xpns_check_cell_size:    Col[]| 2 1 
xpanes:Debug: [2023-01-12_14:42:10]:xpns_check_cell_size:    -----+------------------------...
xpanes:Debug: [2023-01-12_14:42:10]:xpns_execution:Options: '--debug' '-t' '-s' '-c' 'env AWS_PROFILE=staging AWS_REGION=us-west-2 ssh -F /Users/zdAlexM/.ssh/config.zendesk ubuntu_ssm_sudo@{}' '-l' 'ev' 
xpanes:Debug: [2023-01-12_14:42:10]:xpns_execution:Arguments: 'host4' 'host5' 'host6' 
xpanes:Debug: [2023-01-12_14:42:10]:xpns_split_window:Index:2 Argument:host6
xpanes:Debug: [2023-01-12_14:42:10]:xpns_wait_func:mkfifo /Users/zdAlexM/.cache/xpanes/__xpns_sync_68616c6f6e2d72657472792d70726f7879342e706f643939382d31393035350a-2-19055
mkfifo exit status = 0
xpanes:Debug: [2023-01-12_14:42:10]:xpns_wait_func:grep -q 1 '/Users/zdAlexM/.cache/xpanes/__xpns_sync_68616c6f6e2d72657472792d70726f7879342e706f643939382d31393035350a-2-19055' 
xpanes:Debug: [2023-01-12_14:42:10]:xpns_split_window:Index:1 Argument:host5
xpanes:Debug: [2023-01-12_14:42:10]:xpns_wait_func:mkfifo /Users/zdAlexM/.cache/xpanes/__xpns_sync_68616c6f6e2d72657472792d70726f7879342e706f643939382d31393035350a-1-19055
mkfifo exit status = 0
xpanes:Debug: [2023-01-12_14:42:10]:xpns_wait_func:grep -q 1 '/Users/zdAlexM/.cache/xpanes/__xpns_sync_68616c6f6e2d72657472792d70726f7879342e706f643939382d31393035350a-1-19055' 
xpanes:Debug: [2023-01-12_14:42:10]:xpns_split_window:Index:0 Argument:host4
xpanes:Debug: [2023-01-12_14:42:10]:xpns_wait_func:mkfifo /Users/zdAlexM/.cache/xpanes/__xpns_sync_68616c6f6e2d72657472792d70726f7879342e706f643939382d31393035350a-0-19055
mkfifo exit status = 0
xpanes:Debug: [2023-01-12_14:42:10]:xpns_wait_func:grep -q 1 '/Users/zdAlexM/.cache/xpanes/__xpns_sync_68616c6f6e2d72657472792d70726f7879342e706f643939382d31393035350a-0-19055' 
xpanes:Debug: [2023-01-12_14:42:10]:xpns_execution:xpns_is_window_alive:1: After window separation
xpanes:Debug: [2023-01-12_14:42:10]:xpns_execution:xpns_is_window_alive:2: After logging
xpanes:Debug: [2023-01-12_14:42:10]:xpns_inject_title:target_pane=68616c6f6e2d72657472792d70726f7879342e706f643939382d31393035350a.0 pane_title=host4 pane_tty=/dev/ttys017
xpanes:Debug: [2023-01-12_14:42:10]:xpns_inject_title:target_pane=68616c6f6e2d72657472792d70726f7879342e706f643939382d31393035350a.1 pane_title=host5 pane_tty=/dev/ttys016
xpanes:Debug: [2023-01-12_14:42:10]:xpns_inject_title:target_pane=68616c6f6e2d72657472792d70726f7879342e706f643939382d31393035350a.2 pane_title=host6 pane_tty=/dev/ttys015
xpanes:Debug: [2023-01-12_14:42:10]:xpns_notify:Notify to /Users/zdAlexM/.cache/xpanes/__xpns_sync_68616c6f6e2d72657472792d70726f7879342e706f643939382d31393035350a-0-19055
xpanes:Debug: [2023-01-12_14:42:10]:xpns_notify:Notify to /Users/zdAlexM/.cache/xpanes/__xpns_sync_68616c6f6e2d72657472792d70726f7879342e706f643939382d31393035350a-1-19055
xpanes:Debug: [2023-01-12_14:42:10]:xpns_execution:xpns_is_window_alive:3: After setting title
xpanes:Debug: [2023-01-12_14:42:10]:xpns_notify:Notify to /Users/zdAlexM/.cache/xpanes/__xpns_sync_68616c6f6e2d72657472792d70726f7879342e706f643939382d31393035350a-2-19055
xpanes:Debug: [2023-01-12_14:42:10]:xpns_execution:xpns_is_window_alive:4: After sending commands
xpanes:Debug: [2023-01-12_14:42:10]:xpns_clean_session:file = /Users/zdAlexM/.cache/xpanes/socket.*
xpanes:Debug: [2023-01-12_14:42:10]:xpns_clean_session:socket(/Users/zdAlexM/.cache/xpanes/socket.*) is not running. Remove it
```

Adding a `sleep 0.5` after the `mkfifo` makes the issue less apparent but also slows down execution by a lot.

(Another, perhaps problematic, factor, is the corporate security software on the machine — if you cannot reproduce this then I'll probably close this issue and place the root cause in that software)

**Comment by greymd** [comment] 2023-01-13 11:48
Thank you for sharing.

Somehow this issue is not reproduced in my environment.
Even though my environment is the similar one to yours (macOS and arm64-apple-darwin21 bash)

My one is M1 macOS Monterey
```
$ sysctl kern.version
kern.version: Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:46 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T8101
$ /usr/bin/env bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.
$ xpanes --version
xpanes 4.1.3
```


> Adding a sleep 0.5 after the mkfifo makes the issue less apparent but also slows down execution by a lot.
> (Another, perhaps problematic, factor, is the corporate security software on the machine — if you cannot reproduce this then I'll probably close this issue and place the root cause in that software)

I am not so sure what is happening on your machine. However, it is quite interesting to note that you have improved by adding sleep.
I guess... for some reason, running the `mkfifo` command continuously might be causing a time lag in the creation of the named pipe file (It could be security software as you mentioned, or something else).

How about editing `xpns_wait_func` as follows?
It waits for the creation of a named pipe for up to 1 second.
If it is created immediately, processing is immediate.

```bash
xpns_wait_func() {
  local _wait_id="$1"
  local _fifo="${XP_CACHE_HOME}/__xpns_${_wait_id}"
  local _arr=("$_fifo")
  local _fifo_arg=
  _fifo_arg=$(xpns_arr2args "${_arr[@]}")
  xpns_msg_debug "mkfifo $_fifo"
  ## Comment out
  # mkfifo "${_fifo}"
  mkfifo "${_fifo}" >&2
  local i=0
  while ! [[ -e "${_fifo}" ]]; do
    if (( ++i == 10 ));then
      xpns_msg_warning "Failed to create ${_fifo}"
      return
    fi
    sleep 0.1
  done
  xpns_msg_debug "grep -q 1 ${_fifo_arg}"
  printf "%s\\n" "grep -q 1 ${_fifo_arg}"
}
```

If it can mitigate the issue, I will include it in the next release.

**Comment by zdAlexM** [comment] 2023-01-17 17:40
Ah sorry, forgot to include kern.version — this is the latest version allowed by my system administrator's policy:
```
$ sysctl kern.version
kern.version: Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:13 PST 2022; root:xnu-8020.240.14~1/RELEASE_ARM64_T6000
```

A quick experiment earlier adding `ls  -al ${_fifo}` shows that the FIFO is indeed getting created on the disk, leading me to think that `grep` is mistaken in concluding "no such file or directory".

Since this seems to be specific to my machine, and leaving off `-s` mode is sufficient to work around the warning, I think closing this without changing anything is alright.

**Comment by greymd** [comment] 2023-01-17 20:15
I understand.
If anyone else reports the same problem, I would like to further investigate the event in depth.
I would like to close this Issue for now.

Thanks a lot.

**Closed as completed by greymd** 2023-01-17 20:15 UTC

**Comment by greymd** [comment] 2023-03-13 17:45
Hi @zdAlexM 

The latest version, [v4.1.4](https://github.com/greymd/tmux-xpanes/releases/tag/v4.1.4), the feature `--interval` option is implemented.
This may be used as a work-around for this problem.
For example, the following alias can be specified to sleep for 0.2 second for each pane creation or execution of each command.

```bash
alias xpanes='xpanes --interval 0.2'
```

Please make use of this.

**Comment by zdAlexM** [comment] 2023-03-13 18:20
Hi @greymd ! Thanks for the update, the feature is appreciated.
